Spring:
    application:
          name: movie-tick-booking-system-api
            
            // Configuration File
    datasource:
            url: "${MYSQL_URL:jdbc:mysql://localhost:3306/movie-tick-booking-api?createDatabaseIfNotExist=true}"
            username: "${MYSQL_USERNAME:root}"
            password: "${MYSQL_PASSWORD:root}"
    jpa:
            show-sql: true
            hibernate:
              ddl-auto: update

            properties:
              hibernate:
                format_sql: true
app :
  token :
    secret: "${TOKEN_SECRET:K/SFvQsVTpKyBqJ+LB1iyrGbF7RcN5hghXXZ+zirpyc=\n}"
          # Only for testing and development Mode


