Spring:
    application:
          name: movie-tick-booking-system-api
            
            // Configuration File
    datasource:
            url: jdbc:mysql://localhost:3306/movie-tick-booking-api?createDatabaseIfNotExist=true
            username: root
            password: root
    jpa:
            show-sql: true
            hibernate:
              ddl-auto: update
            properties:
              hibernate:
                format_sql: true




